const items = [
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/A31B12538_large.png",
    manifestId: 12538,
    name: "Psi-Rider",
    rarity: "Epic",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1200,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/791612535_large.png",
    manifestId: 12535,
    name: "Psi-blade",
    rarity: "Epic",
    storeCategory: "BRSpecialFeatured",
    vBucks: 0,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/8CA55214_large.png",
    manifestId: 5214,
    name: "Snap",
    rarity: "Handmade",
    storeCategory: "BRSpecialFeatured",
    vBucks: 200,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/6C1B12512_large.png",
    manifestId: 12512,
    name: "Chimichanga!",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 300,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/B82C12708_large.png",
    manifestId: 12708,
    name: "Silver Surfer",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1500,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/88CE12719_large.png",
    manifestId: 12719,
    name: "Hulk Smashers",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1200,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/921A12783_large.png",
    manifestId: 12783,
    name: "The Devil's Wings",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/5F2F12782_large.png",
    manifestId: 12782,
    name: "Daredevil's Billy Clubs",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/237112511_large.png",
    manifestId: 12511,
    name: "Dragacorn",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1500,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/F58B12710_large.png",
    manifestId: 12710,
    name: "Silver Surfer Pickaxe",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/BBA912523_large.png",
    manifestId: 12523,
    name: "Ravenpool",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1500,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/66B512757_large.png",
    manifestId: 12757,
    name: "Blade",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 0,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/3AB912536_large.png",
    manifestId: 12536,
    name: "Probability Dagger",
    rarity: "Epic",
    storeCategory: "BRSpecialFeatured",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/01D612532_large.png",
    manifestId: 12532,
    name: "Unstoppable Force",
    rarity: "Epic",
    storeCategory: "BRSpecialFeatured",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/FF4112533_large.png",
    manifestId: 12533,
    name: "Domino",
    rarity: "Epic",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1500,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/8AC412524_large.png",
    manifestId: 12524,
    name: "Cuddlepool",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1500,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/2F5E12756_small.png",
    manifestId: 12756,
    name: "Daywalker's Kata",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 300,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/7FB012709_large.png",
    manifestId: 12709,
    name: "Silver Surfer's Surfboard",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/17AB12781_large.png",
    manifestId: 12781,
    name: "Daredevil",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1500,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/B97412534_large.png",
    manifestId: 12534,
    name: "Cable",
    rarity: "Epic",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1500,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/B16B12537_large.png",
    manifestId: 12537,
    name: "Psylocke",
    rarity: "Epic",
    storeCategory: "BRSpecialFeatured",
    vBucks: 0,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/1E7912758_large.png",
    manifestId: 12758,
    name: "Dayflier",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1200,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/A94A12510_large.png",
    manifestId: 12510,
    name: "Meaty Mallets",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/AAA612621_large.png",
    manifestId: 12621,
    name: "Captain America",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 2000,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/301812622_large.png",
    manifestId: 12622,
    name: "Grand Salute",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 300,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/FB8011908_large.png",
    manifestId: 11908,
    name: "Signature Sniper",
    rarity: "Handmade",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/6F0D11909_large.png",
    manifestId: 11909,
    name: "Lt. Logo",
    rarity: "Handmade",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/30AF11910_large.png",
    manifestId: 11910,
    name: "Marked Marauder",
    rarity: "Handmade",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/44E211906_large.png",
    manifestId: 11906,
    name: "Symbol Stalwart",
    rarity: "Handmade",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/1A4E11902_large.png",
    manifestId: 11902,
    name: "Emblematic",
    rarity: "Handmade",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 500,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/91E111901_large.png",
    manifestId: 11901,
    name: "Banner Cape",
    rarity: "Rare",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 400,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/05F312205_large.png",
    manifestId: 12205,
    name: "Banner Shield",
    rarity: "Rare",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 400,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/DDF012320_large.png",
    manifestId: 12320,
    name: "Banner Wave",
    rarity: "Rare",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 500,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/00D411904_large.png",
    manifestId: 11904,
    name: "Custom Cruiser",
    rarity: "Handmade",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 500,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/856511905_large.png",
    manifestId: 11905,
    name: "Sgt. Sigil",
    rarity: "Handmade",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/84D711903_large.png",
    manifestId: 11903,
    name: "Branded Brigadier",
    rarity: "Handmade",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/7CF212565_large.png",
    manifestId: 12565,
    name: "Banner",
    rarity: "Rare",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 500,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/F53711907_large.png",
    manifestId: 11907,
    name: "Banner Trooper",
    rarity: "Handmade",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/197811900_large.png",
    manifestId: 11900,
    name: "Branded Brawler",
    rarity: "Handmade",
    storeCategory: "BRWeeklyStorefront",
    vBucks: 800,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/41751963_large.png",
    manifestId: 1963,
    name: "Dark Vanguard",
    rarity: "Fine",
    storeCategory: "BRDailyStorefront",
    vBucks: 2000,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/557512597_small.png",
    manifestId: 12597,
    name: "Paddle Royale",
    rarity: "uncommon",
    storeCategory: "BRDailyStorefront",
    vBucks: 200,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/6E0A6371_large.png",
    manifestId: 6371,
    name: "Busy",
    rarity: "Sturdy",
    storeCategory: "BRDailyStorefront",
    vBucks: 500,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/C4C311952_large.png",
    manifestId: 11952,
    name: "Bachii",
    rarity: "Rare",
    storeCategory: "BRDailyStorefront",
    vBucks: 1200,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/32F81247_large.png",
    manifestId: 1247,
    name: "Make it Rain",
    rarity: "Sturdy",
    storeCategory: "BRDailyStorefront",
    vBucks: 500,
    rating: 0,
    numReviews: 0,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/E8A36483_large.png",
    manifestId: 6483,
    name: "Magic Wings",
    rarity: "Quality",
    storeCategory: "BRDailyStorefront",
    vBucks: 1200,
    rating: 0,
    numReviews: 0,
  },
];

export default items;
