const items = [
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/A31B12538_large.png",
    manifestId: 12538,
    name: "Psi-Rider",
    rarity: "Epic",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1200,
    rating: 4.0,
    numReviews: 3,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/791612535_large.png",
    manifestId: 12535,
    name: "Psi-blade",
    rarity: "Epic",
    storeCategory: "BRSpecialFeatured",
    vBucks: 0,
    rating: 3.5,
    numReviews: 5,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/8CA55214_large.png",
    manifestId: 5214,
    name: "Snap",
    rarity: "Handmade",
    storeCategory: "BRSpecialFeatured",
    vBucks: 200,
    rating: 3,
    numReviews: 12,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/6C1B12512_large.png",
    manifestId: 12512,
    name: "Chimichanga!",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 300,
    rating: 5,
    numReviews: 12,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/B82C12708_large.png",
    manifestId: 12708,
    name: "Silver Surfer",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1500,
    rating: 3.5,
    numReviews: 10,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/88CE12719_large.png",
    manifestId: 12719,
    name: "Hulk Smashers",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1200,
    rating: 4,
    numReviews: 12,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/921A12783_large.png",
    manifestId: 12783,
    name: "The Devil's Wings",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 800,
    rating: 4,
    numReviews: 3,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/5F2F12782_large.png",
    manifestId: 12782,
    name: "Daredevil's Billy Clubs",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 800,
    rating: 4,
    numReviews: 9,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/237112511_large.png",
    manifestId: 12511,
    name: "Dragacorn",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1500,
    rating: 4,
    numReviews: 12,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/F58B12710_large.png",
    manifestId: 12710,
    name: "Silver Surfer Pickaxe",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 800,
    rating: 4,
    numReviews: 12,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/BBA912523_large.png",
    manifestId: 12523,
    name: "Ravenpool",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 1500,
    rating: 4,
    numReviews: 12,
  },
  {
    imageUrl: "https://trackercdn.com/legacycdn/fortnite/66B512757_large.png",
    manifestId: 12757,
    name: "Blade",
    rarity: "marvel",
    storeCategory: "BRSpecialFeatured",
    vBucks: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default items;
